### ISSUE TITLE
Unable to locate publishable resources.

### ISSUE THREAD

**Issue by newtongamajr** [mastani/nova-password-reset#1]
Hi @mastani 

After installing the package, publishing was not concluded and the error presented above was shown:

newton@newton-VirtualBox:~/git/laravel/nova/galileo$ php artisan vendor:publish --force --provider=Mastani\NovaPasswordReset\ToolServiceProvider
Unable to locate publishable resources.
Publishing complete.

**Comment by newtongamajr** [comment]
Hi @mastani,

As I was working on improvements to your package I discovered that the problem is just documentation:

`php artisan vendor:publish --force --provider="Mastani\NovaPasswordReset\ToolServiceProvider" --tag="nova-views"`

I suggest you include information about the use of this publishment. In my case, I've already had a modification on the same view because of the use of another package, and the use of --force would let me loose this.

**Comment by mastani** [comment]
Hi @newtongamajr,

Thanks for your suggestions, I updated the readme and included a notice about that.
Have a nice day!
