### ISSUE TITLE
Password Change fails due to validation

### ISSUE THREAD

**Issue by exophunk** [mastani/nova-password-reset#7]
Probably has to do with some change to the Laravel framework, maybe [this one or so](https://github.com/laravel/framework/blob/8.x/CHANGELOG-8.x.md#v8780-2022-01-04)

Steps:
1. Change Password with your tool
2. Fails with 500, Error appears: `Method Illuminate\Validation\Validator::validatePassword does not exist`

Reason:
https://github.com/mastani/nova-password-reset/blob/master/src/Http/Requests/PasswordResetRequest.php#L25

`'current_password' => 'required|password',`
must be replaced with
`'current_password' => ['required', Password::default()],`

Thanks for fixing!

**Comment by mastani** [comment]
Thanks for bringing it up. Could you please draft a pull request with the changes?

**Comment by exophunk** [comment]
Of course you are right, lazy me. I've added a pull request

**Comment by mastani** [comment]
Thank you so much @exophunk
